# SocialChirp основной функционал:
# - создать пост
# - получить список постов
# - создать комментарий
# - получить список комментариев
# - репост
# - подписка на человека
# - отписка


# на будущее
# - удаление поста
# - удаление комментария

openapi: 3.0.0
info:
  title: SocialChirp
  version: 1.0.0
components:
  schemas:
    Chirp:
      type: object
      properties:
        content:
          type: string
        comments_count:
          type: string
        rechirps_count:
          type: string
        user:
          type: object
          properties:
            id:
              type: string
            fullName:
              type: string
        created_at:
          type: string
          format: date
    Comment:
      type: object
      properties:
        content:
          type: string
        user:
          type: object
          properties:
            id:
              type: string
            fullName:
              type: string
        created_at:
          type: string
          format: date
    Subscriber:
      type: object
      properties:
        id:
            type: string
        fullName:
              type: string
        age:
              type: number
paths:
  /chirps:
    post:
      summary: Create a chirp
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          schema:
            type: string
        - name: content
          in: body
          description: Chirp content
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
      responses:
        '201':
          description: Chirp created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized

  /chirps:
    get:
      summary: Get a list of chirps
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chirp'
        '401':
          description: Unauthorized

    /comments:
    post:
      summary: Create a new comment
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chirp_id
                - user_id
                - content
              properties:
                chirp_id:
                  type: string
                user_id:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: Comment created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized

    /comments:
    get:
      summary: Get comments for chirp
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chirp_id
              properties:
                chirp_id:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '401':
          description: Unauthorized

    /rechirp:
    post:
      summary: Do repost
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chirp_id
                - user_id
              properties:
                chirp_id:
                  type: string
                user_id:
                  type: string
      responses:
        '201':
          description: Rechirp created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
    
    /subscribers:
    get:
      summary: Get a list of subscribers
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscriber'
        '401':
          description: Unauthorized
    /subscribe:
    post:
      summary: Subscribe to person
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - subscriber_id
                - user_id
              properties:
                subscriber_id:
                  type: string
                user_id:
                  type: string
      responses:
        '201':
          description: Subscription was successful
        '400':
          description: Bad request
        '401':
          description: Unauthorized
    /unsubscribe:
    post:
      summary: Unsubscribe from person
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - subscriber_id
                - user_id
              properties:
                subscriber_id:
                  type: string
                user_id:
                  type: string
      responses:
        '201':
          description: Unsubscription was successful
        '400':
          description: Bad request
        '401':
          description: Unauthorized


