# SocialChirp основной функционал:
# - создать пост
# - получить список постов
# - создать комментарий
# - получить список комментариев
# - репост
# - подписка на человека
# - отписка

# на будущее
# - удаление поста
# - удаление комментария

swagger: "2.0"
info:
  title: SocialChirp
  description: "Twitter type application"
  version: 1.0.0
consumes:
  - application/io.goswagger.examples.todo-list.v1+json
produces:
  - application/io.goswagger.examples.todo-list.v1+json
schemes:
  - http
paths:
  /chirps:
    post:
      summary: Create a chirp
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          type: string
        - name: content
          in: body
          description: Chirp content
          required: true
          schema:
            type: object
            properties:
              content:
                type: string
      responses:
        "201":
          description: Chirp created successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized

    get:
      summary: Get a list of chirps
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          type: string
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            items:
              $ref: "#/definitions/Chirp"
        "401":
          description: Unauthorized

  /comments:
    post:
      summary: Create a new comment
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chirp_id
                - user_id
                - content
              properties:
                chirp_id:
                  type: string
                user_id:
                  type: string
                content:
                  type: string
      responses:
        "201":
          description: Comment created successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized

    get:
      summary: Get comments for chirp
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chirp_id
              properties:
                chirp_id:
                  type: string
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            items:
              $ref: "#/definitions/Comment"
        "401":
          description: Unauthorized

  /rechirp:
    post:
      summary: Do repost
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chirp_id
                - user_id
              properties:
                chirp_id:
                  type: string
                user_id:
                  type: string
      responses:
        "201":
          description: Rechirp created successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized

  /contacts:
    get:
      summary: Get a list of subscribers
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          type: string
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            items:
              $ref: "#/definitions/Contact"
        "401":
          description: Unauthorized

  /subscribe:
    post:
      summary: Subscribe to a person
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - contact_id
                - user_id
              properties:
                contact_id:
                  type: string
                user_id:
                  type: string
      responses:
        "201":
          description: Subscription was successful
        "400":
          description: Bad request
        "401":
          description: Unauthorized

  /unsubscribe:
    post:
      summary: Unsubscribe from a person
      parameters:
        - name: Authorization
          in: header
          description: JWT Authorization Token
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - contact_id
                - user_id
              properties:
                contact_id:
                  type: string
                user_id:
                  type: string
      responses:
        "201":
          description: Unsubscription was successful
        "400":
          description: Bad request
        "401":
          description: Unauthorized
definitions:
  Chirp:
    type: object
    description: A Chirp represents a post on SocialChirp.
    properties:
      content:
        type: string
        description: The content of the chirp
      comments_count:
        type: string
        description: The number of comments on the chirp
      rechirps_count:
        type: string
        description: The number of rechirps (reposts) of the chirp
      user:
        $ref: "#/definitions/User"
      created_at:
        type: string
        format: date
        description: The date and time when the chirp was created
    example:
      content: "This is a sample chirp."
      comments_count: "5"
      rechirps_count: "10"
      user:
        id: "123"
        fullName: "John Doe"
      created_at: "2023-10-16T12:34:56Z"

  Comment:
    type: object
    description: A Comment represents a comment on a chirp.
    properties:
      content:
        type: string
        description: The content of the comment
      user:
        $ref: "#/definitions/User"
      created_at:
        type: string
        format: date
        description: The date and time when the comment was created
    example:
      content: "This is a sample comment."
      user:
        id: "456"
        fullName: "Jane Smith"
      created_at: "2023-10-17T13:45:00Z"

  Contact:
    type: object
    description: A Contact represents a user who you follow.
    properties:
      id:
        type: string
      fullName:
        type: string
      age:
        type: number
    example:
      id: "789"
      fullName: "Alice Johnson"
      age: 30

  User:
    type: object
    description: A User represents a registered user of SocialChirp.
    properties:
      id:
        type: string
      fullName:
        type: string
      age:
        type: number
    example:
      id: "123"
      fullName: "John Doe"
      age: 30
